"""Initial migration

Revision ID: 43362f4beac2
Revises: 
Create Date: 2026-07-17 22:54:55.606821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43362f4beac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'completed', 'failed', 'cancelled', name='download_status'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('speed', sa.String(length=64), nullable=True),
    sa.Column('eta', sa.String(length=64), nullable=True),
    sa.Column('format_id', sa.String(length=64), nullable=True),
    sa.Column('quality', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('media_type', sa.Enum('video', 'audio', name='media_type'), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloads_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'user_id', name='uq_setting_key_user')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='log_level'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('download_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['download_id'], ['downloads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_download_id'), ['download_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_logs_source'))
        batch_op.drop_index(batch_op.f('ix_logs_level'))
        batch_op.drop_index(batch_op.f('ix_logs_download_id'))
        batch_op.drop_index(batch_op.f('ix_logs_created_at'))

    op.drop_table('logs')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloads_user_id'))
        batch_op.drop_index(batch_op.f('ix_downloads_status'))
        batch_op.drop_index(batch_op.f('ix_downloads_playlist_id'))
        batch_op.drop_index(batch_op.f('ix_downloads_platform'))
        batch_op.drop_index(batch_op.f('ix_downloads_media_type'))
        batch_op.drop_index(batch_op.f('ix_downloads_created_at'))
        batch_op.drop_index(batch_op.f('ix_downloads_celery_task_id'))

    op.drop_table('downloads')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
